config/routes.rb
require "sidekiq/web"

FlorilegesPrairies::Application.routes.draw do
  resources :woods

  resources :observations

  resources :taxa, defaults: {format: :json}

  resources :sites do
    member do
      patch :export
      put :export
      post :export
    end
    resources :gestions
    resources :releves
  end

  post "export" => "sites#export", as: :export
  post "admin_export" => "admin/actions#admin_export", as: :admin_export

  resources :sites

  get "tous-les-sites", to: "sites#all"

  root :to => "home#index"

  get "menupush", to: "home#menupush"
  get "recherche-taxref", to: "home#/recherche-taxref"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  namespace :admin do
    resources :users, only: :show do
      post :generate_new_password_email
    end
    resources :actions, only: :index
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :releve

  belongs_to :taxon

  # ---- CALLBACKS ----
  after_touch :sync_site_id_cache

  private

  def sync_site_id_cache
    @owner_cache = nil
    @site_cache = nil
    if releve.present?
      if releve.site.present?
        site_cache = releve.site.id
        if releve.site.users.any?
          owner_cache = releve.site.users.first.id
        end
      end
    end

    update_attributes(
      site_owner_id_cache: owner_cache,
      site_id_cache: site_cache,
    )
    puts "Observation##{id} was touched"
  end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_observation, only: [:show, :edit, :update, :destroy]
  before_filter :set_export_mode, only: [:index]

  # GET /observations
  # GET /observations.json
  def index
    # @observations = Observation.all
    email = current_user.email
    if params[:content]=='user'
      @observations = Observation.joins{releve.site.users}.where{{releve.site.users.email => email}}
    elsif params[:content]=='all'
      @valid_obs = Observation.where('taxon_id IS NOT NULL')
      @observations = @valid_obs.joins{releve.site.users}.order{ releve.date.asc  }
      # @observations = @valid_obs.joins{releve.site.users}.where{releve.site.users.email != 'gaetan@florileges.info'}.order{releve.date.asc}
    end
    # @observations = Observation.joins{releve.site.users}.where{created_at >= 7.months.ago}
    # @observations = Observation.joins{releve.site.users}.where{releve.date >= 7.months.ago}
    # @observations = Observation.joins{releve.site.users}.where{releve.site.users.email != 'gaetan@florileges.info'}.order{ releve.date.asc  }
    
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"florileges-prairies-export-observations.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
      format.xlsx
    end

  end

  # GET /observations/1
  # GET /observations/1.json
  def show
  end

  # GET /observations/new
  def new
    @observation = Observation.new
  end

  # GET /observations/1/edit
  def edit
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(observation_params)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @observation }
      else
        format.html { render action: 'new' }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1
  # PATCH/PUT /observations/1.json
  def update
    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_export_mode
      params[:content] ||= 'user'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def observation_params
      params.require(:observation).permit(:q0, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :p, :releve_id, :taxon_id, :created_at, :updated_at, :CD_NOM, :CD_REF, :LB_NOM, :NOM_VALIDE, :florileges, :TAXREF_V)
    end
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/observations/_form.html.erb
<%= simple_form_for(@observation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :q0 %>
    <%= f.input :q1 %>
    <%= f.input :q2 %>
    <%= f.input :q3 %>
    <%= f.input :q4 %>
    <%= f.input :q5 %>
    <%= f.input :q6 %>
    <%= f.input :q7 %>
    <%= f.input :q8 %>
    <%= f.input :q9 %>
    <%= f.input :q10 %>
    <%= f.input :p %>
    <%= f.association :espece %>
    <%= f.association :releve %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.csv.erb
	<% headers = [
	'obs_id',
	'site_id',
	'site_code',
	'releve_date',
	'releve_nom',
	'releve_structure',
	'releve_referents_email',
	'releve_time_start',
	'releve_time_end',
	'releve_hauteur',
	'releve_milieux',
	'releve_semis',
	'releve_fauche',
	'releve_fauche_periode',
	'releve_fauche_freq',
	'releve_fauche_export',
	'releve_paturage',
	'releve_paturage_pression',
	'releve_paturage_duree',
	'releve_traitement',
	'releve_pression',
	'obs_LB_NOM',
	'obs_NOM_VALIDE',
	'obs_CD_NOM',
	'obs_CD_REF',
	'obs_florileges_liste',
	'obs_TAXREF_V',
	'obs_q1',
	'obs_q2',
	'obs_q3',
	'obs_q4',
	'obs_q5',
	'obs_q6',
	'obs_q7',
	'obs_q8',
	'obs_q9',
	'obs_q10',
	'obs_hors_q'] %>
<%= CSV.generate_line(headers, {:row_sep => ''}).html_safe %>
<% @observations.each do |obs| %>
<%= CSV.generate_line([
	obs.id,
	obs.releve.site_id,
	obs.releve.site.code,
	obs.releve.date,
	obs.releve.name,
	obs.releve.structure,
	obs.releve.site.users.map { |u| "#{u.email}" }.join("|"),
	obs.releve.time_start.to_s.gsub("01/01/2000 ", '') ,
	obs.releve.time_end.to_s.gsub("01/01/2000 ", '') ,
	obs.releve.hauteur,
	obs.releve.milieux.split('|'),
	obs.releve.semis,
	obs.releve.fauche,
	obs.releve.fauche_periode,
	obs.releve.fauche_freq,
	obs.releve.fauche_export,
	obs.releve.paturage,
	obs.releve.paturage_pression,
	obs.releve.paturage_duree,
	obs.releve.traitement,
	obs.releve.pression,
	obs.taxon.lb_nom,
	obs.taxon.nom_valide,
	obs.taxon.cd_nom,
	obs.taxon.cd_ref,
	obs.taxon.florileges,
	"v8.0",
	obs.q1,
	obs.q2,
	obs.q3,
	obs.q4,
	obs.q5,
	obs.q6,
	obs.q7,
	obs.q8,
	obs.q9,
	obs.q10,
	obs.q0], {:row_sep => ''}).html_safe %>
<% end %>

app/views/observations/index.html.erb
<h1>Listing observations</h1>

<table>
  <thead>
    <tr>
      <th>Q0</th>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th>Q8</th>
      <th>Q9</th>
      <th>Q10</th>
      <th>P</th>
      <th>Espece</th>
      <th>Releve</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @observations.each do |observation| %>
      <tr>
        <td><%= observation.q0 %></td>
        <td><%= observation.q1 %></td>
        <td><%= observation.q2 %></td>
        <td><%= observation.q3 %></td>
        <td><%= observation.q4 %></td>
        <td><%= observation.q5 %></td>
        <td><%= observation.q6 %></td>
        <td><%= observation.q7 %></td>
        <td><%= observation.q8 %></td>
        <td><%= observation.q9 %></td>
        <td><%= observation.q10 %></td>
        <td><%= observation.p %></td>
        <td><%= observation.espece %></td>
        <td><%= observation.releve %></td>
        <td><%= link_to 'Show', observation %></td>
        <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
        <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Observation', new_observation_path %>

app/views/observations/new.html.erb
<h1>New observation</h1>

<%= render 'form' %>

<%= link_to 'Back', observations_path %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q0:</strong>
  <%= @observation.q0 %>
</p>

<p>
  <strong>Q1:</strong>
  <%= @observation.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @observation.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @observation.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @observation.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @observation.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @observation.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @observation.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @observation.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @observation.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @observation.q10 %>
</p>

<p>
  <strong>P:</strong>
  <%= @observation.p %>
</p>

<p>
  <strong>Espece:</strong>
  <%= @observation.espece %>
</p>

<p>
  <strong>Releve:</strong>
  <%= @observation.releve %>
</p>

<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>