config/routes.rb
require "sidekiq/web"

FlorilegesPrairies::Application.routes.draw do
  resources :woods

  resources :observations

  resources :taxa, defaults: {format: :json}

  resources :sites do
    member do
      patch :export
      put :export
      post :export
    end
    resources :gestions
    resources :releves
  end

  post "export" => "sites#export", as: :export
  post "admin_export" => "admin/actions#admin_export", as: :admin_export

  resources :sites

  get "tous-les-sites", to: "sites#all"

  root :to => "home#index"

  get "menupush", to: "home#menupush"
  get "recherche-taxref", to: "home#/recherche-taxref"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  namespace :admin do
    resources :users, only: :show do
      post :generate_new_password_email
    end
    resources :actions, only: :index
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/wood.rb
class Wood < ActiveRecord::Base
  belongs_to :releve

end

app/controllers/woods_controller.rb
class WoodsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_wood, only: [:show, :edit, :update, :destroy]

  # GET /woods
  # GET /woods.json
  def index
    @woods = Wood.all
  end

  def index
    # @observations = Observation.all
    email = current_user.email
    # @observations = Observation.joins{releve.site.users}.where{{releve.site.users.email => email}}
    # @observations = Observation.joins{releve.site.users}.where{created_at >= 7.months.ago}
    # @observations = Observation.joins{releve.site.users}.where{releve.date >= 7.months.ago}
    @woods = Wood.joins{releve.site}.order{ releve.date.asc  }
    


    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"florileges-prairies-export-woods.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end

  end

  # GET /woods/1
  # GET /woods/1.json
  def show
  end

  # GET /woods/new
  def new
    @wood = Wood.new
  end

  # GET /woods/1/edit
  def edit
  end

  # POST /woods
  # POST /woods.json
  def create
    @wood = Wood.new(wood_params)

    respond_to do |format|
      if @wood.save
        format.html { redirect_to @wood, notice: 'Wood was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wood }
      else
        format.html { render action: 'new' }
        format.json { render json: @wood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /woods/1
  # PATCH/PUT /woods/1.json
  def update
    respond_to do |format|
      if @wood.update(wood_params)
        format.html { redirect_to @wood, notice: 'Wood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /woods/1
  # DELETE /woods/1.json
  def destroy
    @wood.destroy
    respond_to do |format|
      format.html { redirect_to woods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wood
      @wood = Wood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wood_params
      params.require(:wood).permit(:q1, :q2, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :total, :releve_id)
    end
end

app/helpers/woods_helper.rb
module WoodsHelper
end

app/views/woods/_form.html.erb
<%= simple_form_for(@wood) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :q1 %>
    <%= f.input :q2 %>
    <%= f.input :q2 %>
    <%= f.input :q3 %>
    <%= f.input :q4 %>
    <%= f.input :q5 %>
    <%= f.input :q6 %>
    <%= f.input :q7 %>
    <%= f.input :q8 %>
    <%= f.input :q9 %>
    <%= f.input :q10 %>
    <%= f.input :total %>
    <%= f.association :releve %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/woods/edit.html.erb
<h1>Editing wood</h1>

<%= render 'form' %>

<%= link_to 'Show', @wood %> |
<%= link_to 'Back', woods_path %>

app/views/woods/index.csv.erb
<% headers = [
	'site_id',
	'site_code',
	'releve_date',
	'woods_id',
	'woods_q1',
	'woods_q2',
	'woods_q3',
	'woods_q4',
	'woods_q5',
	'woods_q6',
	'woods_q7',
	'woods_q8',
	'woods_q9',
	'woods_q10',
	'woods_total',
	'woods_created_at',
	'woods_updated_at'] %>
<%= CSV.generate_line(headers, {:row_sep => ''}).html_safe %>
<% @woods.each do |wood| %>
<%= CSV.generate_line([
	wood.releve.site_id,
	wood.releve.site.code,
	wood.releve.date,
	wood.id,
	wood.q1,
	wood.q2,
	wood.q3,
	wood.q4,
	wood.q5,
	wood.q6,
	wood.q7,
	wood.q8,
	wood.q9,
	wood.q10,
	wood.total,
	wood.created_at,
	wood.updated_at], {:row_sep => ''}).html_safe %>
<% end %>

app/views/woods/index.html.erb
<h1>Listing woods</h1>

<table>
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th>Q8</th>
      <th>Q9</th>
      <th>Q10</th>
      <th>Total</th>
      <th>Releve</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @woods.each do |wood| %>
      <tr>
        <td><%= wood.q1 %></td>
        <td><%= wood.q2 %></td>
        <td><%= wood.q2 %></td>
        <td><%= wood.q3 %></td>
        <td><%= wood.q4 %></td>
        <td><%= wood.q5 %></td>
        <td><%= wood.q6 %></td>
        <td><%= wood.q7 %></td>
        <td><%= wood.q8 %></td>
        <td><%= wood.q9 %></td>
        <td><%= wood.q10 %></td>
        <td><%= wood.total %></td>
        <td><%= wood.releve %></td>
        <td><%= link_to 'Show', wood %></td>
        <td><%= link_to 'Edit', edit_wood_path(wood) %></td>
        <td><%= link_to 'Destroy', wood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wood', new_wood_path %>

app/views/woods/new.html.erb
<h1>New wood</h1>

<%= render 'form' %>

<%= link_to 'Back', woods_path %>

app/views/woods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @wood.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @wood.q2 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @wood.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @wood.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @wood.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @wood.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @wood.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @wood.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @wood.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @wood.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @wood.q10 %>
</p>

<p>
  <strong>Total:</strong>
  <%= @wood.total %>
</p>

<p>
  <strong>Releve:</strong>
  <%= @wood.releve %>
</p>

<%= link_to 'Edit', edit_wood_path(@wood) %> |
<%= link_to 'Back', woods_path %>