config/routes.rb
require "sidekiq/web"

FlorilegesPrairies::Application.routes.draw do
  resources :woods

  resources :observations

  resources :taxa, defaults: {format: :json}

  resources :sites do
    member do
      patch :export
      put :export
      post :export
    end
    resources :gestions
    resources :releves
  end

  post "export" => "sites#export", as: :export
  post "admin_export" => "admin/actions#admin_export", as: :admin_export

  resources :sites

  get "tous-les-sites", to: "sites#all"

  root :to => "home#index"

  get "menupush", to: "home#menupush"
  get "recherche-taxref", to: "home#/recherche-taxref"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  namespace :admin do
    resources :users, only: :show do
      post :generate_new_password_email
    end
    resources :actions, only: :index
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/site.rb
class Site < ActiveRecord::Base


	has_many :ownerships  
  has_many :users, :through => :ownerships
  has_one :photo
  accepts_nested_attributes_for :photo
  has_many :releves

  accepts_nested_attributes_for :ownerships

  

	# geocoded_by :location
	# after_validation :geocode

	mount_uploader :photo, ImageUploader
	# process_in_background :photo

	mount_uploader :plan, ImageUploader
	# process_in_background :plan

	reverse_geocoded_by :latitude, :longitude, :address => :location
	after_validation :reverse_geocode  # auto-fetch address

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end


end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_filter :set_export_mode, :only => [:index]

  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites(:order => "code ASC")
    # @sites = Site.where{updated_at >= 10.months.ago}
    # @sites = Site.joins{users}.where{id >= 39}.order('id ASC')
    @hash = Gmaps4rails.build_markers(@sites) do |site, marker|
      marker.lat site.latitude
      marker.lng site.longitude
      marker.infowindow site.code
    end

    @all_sites = Site.all
    @features = Array.new

    @all_sites.each do |site|
      @features << {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [site.longitude.to_f, site.latitude.to_f],
        },
        properties: {
          :code => site.code,
          :'marker-color' => "#00607d",
          :'marker-symbol' => "circle",
          :'marker-size' => "medium",
        },
      }
    end

    @geojson = {type: "FeatureCollection", features: @features}

    respond_to do |format|
      format.html
      format.csv do
        headers["Content-Disposition"] = "attachment; filename=\"florileges-prairies-export-sites.csv\""
        headers["Content-Type"] ||= "text/csv"
      end
      format.geojson { render json: @geojson }
      format.xlsx
    end
  end

  def all
    authorize! :index, @user, :message => "Not authorized as an administrator."
    @sites = Site.all
    render json: @sites
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @hash = Gmaps4rails.build_markers(@site) do |site, marker|
      marker.lat site.latitude
      marker.lng site.longitude
      marker.infowindow site.code
    end
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
    @hash = Gmaps4rails.build_markers(@site) do |site, marker|
      marker.lat site.latitude
      marker.lng site.longitude
    end
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.create(site_params)
    @site.ownerships.build(owner: "true", user_id: current_user.id)
    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: "Le site de la prairie a été crée avec succès." }
        format.json { render action: "show", status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to sites_url, notice: "Le site a bien été mis à jour." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  # POST /sites/export
  # DELETE /sites/export
  def export
    export = DataExporterService.new(current_user.id)
    export.call
    AdminMailer.export_process_complete(export.user, export.attachment).deliver_now
    respond_to do |format|
      format.html { redirect_to sites_url, notice: "#{export.message}. Dès qu'elles seront prêtes, ces données seront envoyées à l'adresse <#{current_user.email}>" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_export_mode
    params[:content] ||= "user"
  end

  def set_site
    @site = Site.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    params.require(:site).permit(:code, :latitude, :longitude, :location, :created_at, :updated_at, :password, :photo, :public, :plan, :propage, :propage_identifier, :gen_freq, :gen_gest, :gen_obj, :gen_surface, :gestion_date, :hist_date, :hist_occsol, :hist_trav, :cult_amend, :cult_amend_freq, :cult_trav, :cult_trav_freq, :cult_trav_freqinfo, photo_attributes: [:id, :title, :image])
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_list.html.erb
<div class="col-sm-9">
  <ul class="nav nav-pills nav-justified" id="pillSites">
    <li class="filter active"><a href="#liste" data-toggle="pill">
        <h4 class="glyphicon glyphicon-th-list"></h4>
      </a></li>
    <li class="filter"><a href="#carte" data-toggle="pill">
        <h4 class="glyphicon glyphicon-globe"></h4>
      </a></li>
    <!-- <li class="filter"><a href="#stats" data-toggle="pill"><h4 class="glyphicon glyphicon-stats"></h4></a></li> -->
  </ul>
  <div class="tab-content">
    <!-- SITES LIST TAB -->
    <div class="tab-pane active" id="liste">
      <br>
      <% for site in @sites %>
        <div class="the-box-landing border-color-left">
          <div class="row">
            <div class="col-sm-3">
              <%= image_tag site.photo_url(:thumb).to_s, class: 'img-responsive img-circle'  %>
            </div>
            <div class="col-sm-7">
              <h3><%= link_to site.code, site  %></h3>
              <p><i><%= site.location %></i></p>
              <span class="hint"><b>Code de suivi: </b><%= site.code %> | <b>Créé par: </b><i> <%= site.users.first.name %></i></span><hr>
              <div>Vous avez <strong><%= site.releves.length %> fiche de relevés et de gestion</strong> associée à ce site</div>
              <div class="btn btn-primary btn-sm" data-toggle="modal" data-target="#mesReleves<%=site.id%>">
                <i class="glyphicon glyphicon-pencil"></i> Fiche de relevés et de gestion
              </div>
            </div>
            <div class="col-sm-2">
              <div>
                <%= link_to  edit_site_path(site), class:'btn btn-info btn-xs' do %>
                  <i class="glyphicon glyphicon-pencil"></i> Modifier
                <% end %>
              </div>
              <div></div>
              <div>
                <%= link_to site, method: :delete, data: { confirm: "Cette action est définitive. Êtes-vous sûr de vouloir supprimer le site?" }, class:'btn btn-danger btn-xs' do %>
                  <i class="glyphicon glyphicon-remove-sign"></i> Supprimer
                <% end %>
              </div>
              <!-- Modal GESTION-->
              <div class="modal fade" id="mesGestions<%=site.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="maDescriptionLabel">Modifier les fiches-gestions de <b><%= site.code %></b></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End of Modal GESTION-->
              <!-- Modal RELEVÉS-->
              <div class="modal fade" id="mesReleves<%=site.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="maDescriptionLabel">Modifier les fiches-relevés de <b><%= site.code %></b> </h4>
                    </div>
                    <div class="modal-body">
                      <% site.releves.each do |g| %>
                        <div class="fields">
                          <h4>Fiche-relevés en date du <%= g.date %> | <%= link_to "Modifier la fiche", edit_site_releve_path(site,g) %> </h4>
                        </div>
                        <br>
                      <% end %>
                      <div class="action">
                        <% unless site.releves.empty? %>
                          <%= link_to "Créer une nouvelle fiche de relevés", new_site_releve_path(site), class:'btn btn-primary btn-lg center-block' %>
                        <% else %>
                          <%= link_to "Créer votre première fiche de relevés pour cette prairie", new_site_releve_path(site), class:'btn btn-primary btn-lg center-block'%>
                        <% end %>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End of Modal RELEVÉS-->
            </div>
          </div>
        </div>
      <% end %>
      <div class="max-w-sm rounded overflow-hidden shadow-lg">
        <img class="w-full" src="https://source.unsplash.com/random/400x400" alt="Sunset in the mountains">
        <div class="px-6 py-4">
          <div class="font-bold text-xl mb-2">The Coldest Sunset</div>
          <p class="text-gray-700 text-base">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
          </p>
        </div>
        <div class="px-6 py-4">
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
        </div>
      </div>
      <div class="max-w-sm w-full lg:max-w-full lg:flex">
        <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url('/img/card-left.jpg')" title="Woman holding a mug">
        </div>
        <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
          <div class="mb-8">
            <p class="text-sm text-gray-600 flex items-center">
              <svg class="fill-current text-gray-500 w-3 h-3 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M4 8V6a6 6 0 1 1 12 0v2h1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-8c0-1.1.9-2 2-2h1zm5 6.73V17h2v-2.27a2 2 0 1 0-2 0zM7 6v2h6V6a3 3 0 0 0-6 0z" />
              </svg>
              Members only
            </p>
            <div class="text-gray-900 font-bold text-xl mb-2">Can coffee make you a better developer?</div>
            <p class="text-gray-700 text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.</p>
          </div>
          <div class="flex items-center">
            <img class="w-10 h-10 rounded-full mr-4" src="/img/jonathan.jpg" alt="Avatar of Jonathan Reinink">
            <div class="text-sm">
              <p class="text-gray-900 leading-none">Jonathan Reinink</p>
              <p class="text-gray-600">Aug 18</p>
            </div>
          </div>
        </div>
      </div>
      <!-- MAP OF SITES -->
      <div class="tab-pane" id="carte">
        <br>
        <div style="width: auto">
          <div id="map" style="width: auto; height: 400px"></div>
        </div>
      </div>
      <!-- STATS OF SITES -->
      <!--     <div class="tab-pane" id="stats">
      <br>
      <div style="width: auto">
        <div style="width: auto; height: 400px; background: #0000">STATS</div>
      </div>
    </div> -->
    </div>
    <!-- tab content -->
  </div>
  <div class="col-sm-3">
    <div class="the-box-landing border-orange-topbottom">
      <h3 style="text-align: center; padding: 10px 0 0 0;">AJOUTER UN SITE</h3>
      <div class="hi-icon-wrap hi-icon-effect-1 hi-icon-effect-1b">
        <%= link_to 'Nouvelle prairie', new_site_path , class: 'hi-icon hi-icon-location' %>
      </div>
    </div>
    <div class="the-box-landing border-orange-topbottom">
      <h3 style="text-align: center; padding: 10px 0 0 0;">EXPORTER VOS DONNÉES</h3>
      <div style="text-align: center; margin: 10px 10px 10px 20px">
        <%= link_to  sites_path(format: :csv), class:'btn btn-default' do %>
          <i class="glyphicon glyphicon-cloud-download"></i> Télécharger vos sites <br>
          (CSV - UTF8)</br>
      <% end %>
      <div style="margin-top: 10px;"></div>
      <%= link_to  sites_path(format: :xlsx), class:'btn btn-default' do %>
        <i class="glyphicon glyphicon-cloud-download"></i> Télécharger vos sites <br>
        (XLSX)</br>
    <% end %>
    <div style="margin-top: 10px;"></div>
    <%= link_to  observations_path(format: :csv), class:'btn btn-default' do %>
      <i class="glyphicon glyphicon-cloud-download"></i> Télécharger vos observations <br>
      (CSV - UTF8)</br>
  <% end %>
  <div style="margin-top: 10px;"></div>
  <%= link_to  observations_path(format: :xlsx), class:'btn btn-default' do %>
    <i class="glyphicon glyphicon-cloud-download"></i> Télécharger vos observations <br>
    (XLSX)</br>
<% end %>
<!-- Button trigger export modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exportModal">
  <i class="glyphicon glyphicon-send"></i> Export des données </br>
</button>
<!-- Modal -->
<div class="modal fade" id="exportModal" tabindex="-1" role="dialog" aria-labelledby="exportModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exportModalLabel">Export de vos données</h4>
      </div>
      <div class="modal-body tl">
        <p>Vos données seront rassemblés dans 2 tableurs au format XLSX:</p>
        <ul class="list-disc">
          <li>le premier tableur contiendra l'ensemble de vos sites et les données d'historique associées à ces derniers</li>
          <li>le second tableur contiendra l'ensemble des observations, données de gestion par relevé comprises</li>
        </ul>
        <p>Ces 2 fichiers vous seront envoyés à l'adresse électronique associée à votre profil Florilèges, à savoir <<%= @current_user.email %>> </p>
          <p>Si nécessaire, vous pouvez modifier cette adresse électronique depuis les paramètres de votre profil</p>
        </div>
        <div class="modal-footer">
          <div class='inline-block'>
            <button type="button" class="btn btn-default inline-block" data-dismiss="modal">Annuler l'export</button>
          </div>
          <div class='inline-block'>
            <%= button_to export_path, class:'btn btn-primary inline-block' do %>
              <i class="glyphicon glyphicon-send"></i> Envoyer les données </br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Modal -->
</div>
</div>
</div>
<script>
  $('#exportModal').on('show.bs.modal', function (e) {
    console.log(e);
  })
</script>

app/views/sites/edit.html.erb
<h2 class="m-10">MODIFIER LA FICHE LOCALISATION ET HISTORIQUE</h2>
<%= render 'form' %>

app/views/sites/index.csv.erb
<% headers = [
  'site_id',
  'site_code',
  'site_latitude',
  'site_longitude',
  'site_location',
  'site_frequentation',
  'site_gestionnaire',
  'site_surface',
  'site_objectifs',
  'site_date_creation',
  'site_ancien_usage',
  'site_hist_trav',
  'site_amendement',
  'site_amendement_freq',
  'site_travaux',
  'site_travaux_freq',
  'site_propage',
  'id_PROPAGE'] %>
<%= CSV.generate_line(headers, {:quote_char=>'"', :row_sep => ''}).html_safe %>
<% @sites.each do |site| %>
  <%= CSV.generate_line([
    site.id,
    site.code,
    site.latitude,
    site.longitude,
    site.location,
    site.gen_freq,
    site.gen_gest,
    site.gen_surface,
    site.gen_obj.to_s.split('|'),
    site.hist_date,
    site.hist_occsol,
    site.hist_trav,
    site.cult_amend,
    site.cult_amend_freq,
    site.cult_trav,
    site.cult_trav_freq,
    site.propage,
    site.propage_identifier], {:quote_char=>'"', :row_sep => ''}).html_safe %>
<% end %>

app/views/sites/new.html.erb
<%= link_to sites_path, class: "btn btn-danger" do %>
<i class="fa fa-backward"></i>Annuler la création du site
<% end %>
<h1>CRÉER UNE PRAIRIE</h1>
<h2>FICHE LOCALISATION ET HISTORIQUE</h2>

<%= render 'form' %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<!-- FOCUS -->
<div class="row">
  <div class="col-md-5">
    <div class="site-focus">
      <figure class="effect-dexter">
        <%= image_tag @site.photo_url.to_s %>
        <figcaption>
          <h2><%= @site.code %></h2>
          <p><strong>Adresse: </strong><%= @site.location %> <br>
            <strong>Coord GPS: </strong><%= @site.longitude %>,<%= @site.latitude %>
          </p>
          <%= link_to "edit", edit_site_path(@site) %>
        </figcaption>
      </figure>
    </div>
  </div>
  <!-- MAPS AND SKETCH -->
  <div class="col-md-7">
    <ul class="nav nav-pills nav-justified" id="pillSites">
      <li class="filter active"><a href="#carte" data-toggle="pill"><h4 class="glyphicon glyphicon-globe"></h4></a></li>
      <li class="filter"><a href="#sketch" data-toggle="pill"><h4 class="glyphicon glyphicon-picture"></h4></a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="carte">
        <br>
        <div id="map" style='width: auto; height: 315px;background: white'></div>
      </div> 
      <div class="tab-pane" id="sketch">
        <br>
        <% if @site.plan? %>
          <div class="frame-block">
          <div style='width: auto; height: 315px;'> <%= image_tag @site.plan_url(:medium).to_s %> </div>
          </div>
        <% else %>
          Pas d'image
        <% end %>
      </div>
    </div>  

  </div>
  <!-- END OF MAPS AND SKETCH -->
</div>
<br>
<!-- FICHES -->
<div class="row">
  <div class="col-md-6">
    <div class="the-box-landing border-color-left">
      <h3>RÉSUMÉ DU SITE</h3>
    </div>
    <div class="list-block">
      <div style="text-align: center; margin: 10px 10px 10px 20px;">
        <button type="button" class="btn btn-default btn-lg" disabled="disabled">En cours de réalisation...</button>
      </div>
    </div>  
  </div>

  <div class="col-md-6">
    <div class="the-box-landing border-color-left">
      <h3>FICHES DE RELEVÉS ET DE GESTION</h3>
    </div>
    <div class="list-block">
      <ul>
      <% @site.releves.each do |r| %>
        <li>
          <%= link_to edit_site_releve_path(@site,r) do %>
          Fiche-relevés du <%= r.date %>
          <% end %> | 
          <%= link_to site_releve_path(@site,r), :data => { :confirm => "Attention cette action est irréversible! Confirmez-vous la suppresion de la fiche?" }, :method => :delete, class:'btn btn-danger btn-xs' do %>
           <i class="glyphicon glyphicon-remove-sign"></i> Supprimer
          <% end %>  
        </li> 
      <% end %>
      </ul>
      <br>
      
      <div class="action">
        <% unless @site.releves.empty? %>
          <%= link_to "Créer une nouvelle fiche de gestion", new_site_releve_path(@site), class:'btn btn-primary center-block' %>
        <% else %>
          <%= link_to "Créer votre première fiche de relevés", new_site_releve_path(@site), class:'btn btn-primary center-block'%>
        <% end %>
      </div>
    </div> 
  </div>
</div>
<br>
<%= link_to sites_path, class:'btn btn-primary' do %>
  <i class="glyphicon glyphicon-chevron-left"></i> Retour à la liste des sites
<% end %> 
 | 
<%= link_to edit_site_path(@site), class:'btn btn-warning' do %>
  <i class="glyphicon glyphicon-pencil"></i> Modifier
<% end %>

<script>

      function initializeMap() {
        var myLatLng = {lat: <%= @site.latitude %>, lng: <%= @site.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
</script>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_CLOUD_API_KEY']}&callback=initializeMap", {defer: true, async: true} %>